<a href="https://colab.research.google.com/github/darkwingpatil/Ml_hackethons/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Tensor basics

### Setup Steps

In [ ]:
!pip3 install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [ ]:
import torch
import numpy as np

In [ ]:
print(torch.__version__)

2.3.1+cu121


#**Tensor**

###Initializing a tensor

In [ ]:
# Initializing a tensor
a = torch.Tensor([2,3])
print(a.size())
print(a)

torch.Size([2])
tensor([2., 3.])


In [ ]:
a.type()

'torch.FloatTensor'

In [ ]:
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(t)
print(t.size())
print(t.t())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Creating a scalar tensor

In [ ]:
a = torch.tensor(200)
print(a)
print(a.size())
print(a.type())

tensor(200)
torch.Size([])
torch.LongTensor


###Converting scalar to python number

In [ ]:
print(a.item())
print(type(a.item()))

200
<class 'int'>


###Creating a float tensor

In [ ]:
a = torch.tensor([2.0,3])
a.type()

'torch.FloatTensor'

###Providing the data type while creating the tensor

In [ ]:
a = torch.tensor([2,3],dtype=torch.int32)
a.type()

'torch.IntTensor'

###Just like numpy, creating a tensor by copying another tensor results, pointing to same memory location









In [ ]:
a = torch.tensor([2.0, 3])
b = a
c=a.clone()
b[0] = 11
print(a)
print(b)
print(c)

tensor([11.,  3.])
tensor([11.,  3.])
tensor([2., 3.])


###2D tensor

In [ ]:
a = torch.tensor([[1,2],[3,4]])
print(a)
print(a.type())

tensor([[1, 2],
        [3, 4]])
torch.LongTensor


In [ ]:
a = torch.Tensor([[1,2],[3,4]])
print(a)
print(a.type())

tensor([[1., 2.],
        [3., 4.]])
torch.FloatTensor


###Creating and initializing a tensor with random values

In [ ]:
a = torch.rand(3,4)
print(a)

tensor([[0.3676, 0.4424, 0.6463, 0.8486],
        [0.2425, 0.9140, 0.6191, 0.5375],
        [0.6782, 0.3743, 0.9336, 0.3493]])


###Creating and initializing a float tensor with zeros

In [ ]:
a = torch.zeros((4,5), dtype=torch.float32)
print(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


###Creating an Identity tensor

In [ ]:
a = torch.eye(4,4)
print(a)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#**Tensor Operations**

###Addition of two tensor

In [ ]:
x = torch.rand(3,3)
y = torch.rand(3,3)
z = x+y
print(z)

tensor([[1.2519, 0.9201, 0.6100],
        [1.4365, 0.8854, 0.6081],
        [1.6056, 0.6473, 1.7680]])


###Addition of two tensor (alternative)

In [ ]:
z = x.add(y)
print(z)
#z=x+y

tensor([[1.2519, 0.9201, 0.6100],
        [1.4365, 0.8854, 0.6081],
        [1.6056, 0.6473, 1.7680]])


In [ ]:
c=torch.tensor(20)
print(c.size())
c=torch.tensor([20])
print(c.size())
c=torch.tensor([[20]])
print(c.size())
c=torch.tensor([[[20]]])
print(c.size())

torch.Size([])
torch.Size([1])
torch.Size([1, 1])
torch.Size([1, 1, 1])


###Inplace addition of two tensor

In [ ]:
print(x)

x.add_(y)
#x=x+y

print(x)

tensor([[0.8906, 0.3131, 0.3655],
        [0.8425, 0.5667, 0.0413],
        [0.6256, 0.4259, 0.9385]])
tensor([[1.2519, 0.9201, 0.6100],
        [1.4365, 0.8854, 0.6081],
        [1.6056, 0.6473, 1.7680]])


###Element wise multiplication

In [ ]:
print(x*y)

tensor([[0.4523, 0.5585, 0.1492],
        [0.8532, 0.2822, 0.3447],
        [1.5735, 0.1433, 1.4665]])


###Matrix multiplication

In [ ]:
z = torch.matmul(x,y[:,0])
print(z)
z.size()

tensor([1.5966, 1.6409, 2.6972])


torch.Size([3])

###Reshaping tensors

In [ ]:
x = torch.rand(5,6)
print("Size of x :\n",x.size())
print("x:\n",x)
y = x.view(30)
print("Size of y :\n",y.size())
print("y:\n",y)
z = x.view(3,10)
print("Size of z :\n",z.size())
print("z:\n",z)
z = x.view(-1,10)
print("Size of z :\n",z.size())
print("z:\n",z)

Size of x :
 torch.Size([5, 6])
x:
 tensor([[0.4491, 0.0438, 0.7166, 0.3015, 0.6686, 0.6745],
        [0.8546, 0.3482, 0.3754, 0.6935, 0.5071, 0.7120],
        [0.0045, 0.0881, 0.5412, 0.1370, 0.1729, 0.5055],
        [0.1323, 0.1019, 0.1943, 0.2376, 0.5205, 0.3194],
        [0.2996, 0.2427, 0.7999, 0.4581, 0.3465, 0.2511]])
Size of y :
 torch.Size([30])
y:
 tensor([0.4491, 0.0438, 0.7166, 0.3015, 0.6686, 0.6745, 0.8546, 0.3482, 0.3754,
        0.6935, 0.5071, 0.7120, 0.0045, 0.0881, 0.5412, 0.1370, 0.1729, 0.5055,
        0.1323, 0.1019, 0.1943, 0.2376, 0.5205, 0.3194, 0.2996, 0.2427, 0.7999,
        0.4581, 0.3465, 0.2511])
Size of z :
 torch.Size([3, 10])
z:
 tensor([[0.4491, 0.0438, 0.7166, 0.3015, 0.6686, 0.6745, 0.8546, 0.3482, 0.3754,
         0.6935],
        [0.5071, 0.7120, 0.0045, 0.0881, 0.5412, 0.1370, 0.1729, 0.5055, 0.1323,
         0.1019],
        [0.1943, 0.2376, 0.5205, 0.3194, 0.2996, 0.2427, 0.7999, 0.4581, 0.3465,
         0.2511]])
Size of z :
 torch.Size([3, 10]

###Generating Numbers in Sequence

In [ ]:
x = torch.arange(9)
print(x)
x = x.view(3,3)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


###Concatenating two tensors at a given dimension

In [ ]:
print(torch.cat((x,x),dim=0))
print(torch.cat((x,x),dim=1))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]])


###Reducing the redundant dimension by squeeze operation

In [ ]:
x1= torch.rand(1,5)
print("size of x1 squeezing:\n",x1.size())
print(x1)
x1 = x1.squeeze()
print("size of x1 after squeezing:\n", x1.size())
print(x1)

size of x1 squeezing:
 torch.Size([1, 5])
tensor([[0.8146, 0.1355, 0.2786, 0.8531, 0.1111]])
size of x1 after squeezing:
 torch.Size([5])
tensor([0.8146, 0.1355, 0.2786, 0.8531, 0.1111])


In [ ]:
x1 = torch.rand(1,1,5)
print("size of x1 before squeezing:\n", x1.size())
print(x1)
x1 = x1.squeeze()
print("size of x1 after squeezing:\n", x1.size())
print(x1)
print(x1.numpy())

size of x1 before squeezing:
 torch.Size([1, 1, 5])
tensor([[[0.1132, 0.8039, 0.9188, 0.3742, 0.9733]]])
size of x1 after squeezing:
 torch.Size([5])
tensor([0.1132, 0.8039, 0.9188, 0.3742, 0.9733])
[0.11319357 0.8039046  0.9188303  0.37416154 0.97331715]


In [ ]:
x2 = torch.rand(3,1,4,1,5)
print("size of x2 before squeezing:\n", x2.size())
print(x2)
x2 = x2.squeeze()
print("size of x2 after squeezing:\n", x2.size())
print(x2)

size of x2 before squeezing:
 torch.Size([3, 1, 4, 1, 5])
tensor([[[[[0.6104, 0.5581, 0.3383, 0.7517, 0.9724]],

          [[0.2645, 0.4207, 0.9352, 0.1507, 0.5052]],

          [[0.0263, 0.5204, 0.5380, 0.1720, 0.5332]],

          [[0.8278, 0.1382, 0.1746, 0.3785, 0.7850]]]],



        [[[[0.7397, 0.7679, 0.2048, 0.9247, 0.7966]],

          [[0.7449, 0.0478, 0.9821, 0.9419, 0.1817]],

          [[0.1391, 0.2910, 0.1632, 0.7411, 0.5174]],

          [[0.5448, 0.3096, 0.3562, 0.0108, 0.1996]]]],



        [[[[0.1768, 0.0252, 0.2160, 0.5674, 0.9280]],

          [[0.4543, 0.4495, 0.9436, 0.7329, 0.3258]],

          [[0.7061, 0.1305, 0.4379, 0.2049, 0.7900]],

          [[0.8766, 0.1102, 0.6536, 0.7579, 0.7362]]]]])
size of x2 after squeezing:
 torch.Size([3, 4, 5])
tensor([[[0.6104, 0.5581, 0.3383, 0.7517, 0.9724],
         [0.2645, 0.4207, 0.9352, 0.1507, 0.5052],
         [0.0263, 0.5204, 0.5380, 0.1720, 0.5332],
         [0.8278, 0.1382, 0.1746, 0.3785, 0.7850]],

        [[0.739

###Extending the dimension by unsqueeze operation

In [ ]:
x = torch.rand(3,4,5,6)
print(x.size())
#print(x)
print(x.unsqueeze(dim=2).size())
#print(x.unsqueeze(dim=2))
print(x.unsqueeze(dim=3).size())
print(x.unsqueeze(dim=4).size())

torch.Size([3, 4, 5, 6])
torch.Size([3, 4, 1, 5, 6])
torch.Size([3, 4, 5, 1, 6])
torch.Size([3, 4, 5, 6, 1])


###Numpy Bridge
####Converting a numpy array to torch tensor

In [ ]:
x = np.array([[1.0,2],[3,4]])
print(type(x))
y = torch.from_numpy(x)
print(y)
y.type()

<class 'numpy.ndarray'>
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


'torch.DoubleTensor'

####Converting a torch tensor to numpy array

In [ ]:
z = y.numpy()
z.dtype

dtype('float64')

**CUDA Tensors**

####Checking the availability of CUDA/GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
# Linux bash command to print the status of nvidia gpu (memory and processes)
!nvidia-smi

Sat Aug 10 05:04:05 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

####Defining the device object (cpu/gpu)

In [ ]:
device = torch.device("cuda")
x = torch.rand(3,3)
print(x)
x.type()

tensor([[0.8870, 0.9056, 0.2414],
        [0.9167, 0.6942, 0.3483],
        [0.0131, 0.0642, 0.7547]])


'torch.FloatTensor'

In [ ]:
x = x.to(device)
x.type()

'torch.cuda.FloatTensor'


###Transferring the tensor to the respective device (here cpu->gpu)
####Transferring the tensor from gpu->cpu


In [ ]:
# Transferring the tensor from gpu->cpu
device_cpu = torch.device("cpu")
x = x.to(device_cpu)
x.type()

'torch.FloatTensor'

In [1]:
import torch
from torch.autograd import Variable
# rows
N=100
# col
D_in=10
# hidden
H=100
# output
D_out=1
#  WE ARE DOING REGRESSION
x = Variable(torch.randn(N, D_in), requires_grad=False)
y = Variable(torch.randn(N, D_out), requires_grad=False)
w1 = Variable(torch.randn(D_in,H), requires_grad=True)
w2 = Variable(torch.randn(H, D_out), requires_grad=True)
b1 = Variable(torch.randn(H), requires_grad=True)
b2 = Variable(torch.randn(D_out), requires_grad=True)
learning_rate = 1e-5

for t in range(5000):
    # FP
      #  ST= X*W1 +BIAS
      #  ACTIVATION(ST)
    y_pred = ((x.mm(w1)+b1).clamp(min=0).mm(w2)+b2) #FP  NOT APPLYING ACTIVATION
    loss = (y_pred-y).pow(2).sum() #Loss computation MEAN SQUARED EROR
    loss.backward() #BP
    w2.data -= learning_rate*w2.grad #WU
    w1.data -= learning_rate*w1.grad #WU
    b2.data -= learning_rate*b2.grad #WU
    b1.data -= learning_rate*b1.grad #WU
    w1.grad.data.zero_() #Reset gradients
    w2.grad.data.zero_() #Reset gradients
    b1.grad.data.zero_() #Reset gradients
    b2.grad.data.zero_() #Reset gradients
    if t%100==0:
      print(loss)
      print(loss.type())

tensor(56018.0625, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(1046.3306, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(415.3498, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(230.8835, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(147.5284, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(102.6503, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(75.9411, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(58.9970, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(47.2783, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(38.7816, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(32.4325, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(27.5347, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(23.6353, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(20.4655, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(17.8550, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(15.6842, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(13.8737, grad_fn=<SumBackward0>)
torch.FloatTensor
tenso

In [2]:
print(x.mm)

<built-in method mm of Tensor object at 0x7df4e5d3fbf0>
